# Generated by Django 3.2.7 on 2021-09-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Логин пользователя в Telegram')),
                ('name', models.CharField(max_length=64, verbose_name='Имя пользователя в Telegram')),
            ],
            options={
                'verbose_name': 'Доступ пользователю',
                'verbose_name_plural': 'Доступ пользователям',
                'db_table': 'allowed_users',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.PositiveIntegerField(default=0, verbose_name='Время создания')),
                ('date_update', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время последнего изменения')),
                ('room_name', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Название кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.PositiveIntegerField(default=0, verbose_name='Время создания')),
                ('date_update', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время последнего изменения')),
                ('day', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время конца')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room', verbose_name='Кабинет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.alloweduser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'booking',
            },
        ),
    ]
